 default: &default
   adapter: mysql2
   encoding: utf8
   pool: 5
   username: linkage                # wifiadmin
   password:  '!QAZ2wsx'            #wifiadmin50
   host: localhost

 development:
   <<: *default
   database: xiuniang


test:
      <<: *default
      database: xiuniang

 production:
   <<: *default
   database: xiuniang

