default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/development.sqlite3


# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: linkage
#   password:  !QAZ2wsx
#   host: localhost
#
# production:
#   <<: *default
#   database: xiuniang
#
# test:
#   <<: *default
#   database: xiuniang
#
# development:
#   <<: *default
#   database: xiuniang
