# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8be0ba01c1c7f97135befa2c7b07c0a22ee223e2e1b26595919aac321b85856ec0d70d5981a1b2ea77141fa8f115d2d27f0ce7de01eca148a920377299c9cbec

test:
  secret_key_base: 865370577674028e86a8083333d7be50678bb67e3b7916266ba03d7eec1a6ad1bb55d82c6ba186836b2ee8eb6f91ce810c861854980447fcc8753c9fd7aa22ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
